### PR TITLE
Stream log example

### PR DESCRIPTION
**Pull request by pchico83**

### CODE REVIEW

**Comment by fermayo** [comment]
we should also include an example of the logs of a service

**Comment by pchico83** [comment]
@fermayo updated

**Comment by fermayo** [comment]
they do have `streamType` right?

**Comment by Siedrix** [comment]
This is a container log message ```{"type":"log","log":"2015-06-08T16:02:04.434135025Z Hello\n","streamType":"stdout","timestamp":1433779324}```

And this is a services log message ```{"type":"log","source":"ubuntu-157a160f-1","log":"2015-06-08T16:02:04.434135025Z Hello\n","streamType":"stdout","timestamp":1433779324}```

**Comment by Siedrix** [comment]
This are the messages that a services gets. 

screen shot 2015-06-08 at 12 18 22 pm

When containers gets connected, logs and then when all containers are ready you get the `log-started`

**Comment by pchico83** [comment]
@Siedrix can you review again? including action log sample?

**Pull request merged**
